export interface typeMappings {
	[key: string]: {
		[key: string]: string;
	};
}

export const typeMappings: typeMappings = {
	int: {
		python: "int",
		javascript: "number",
		java: "int",
		cpp: "int",
		csharp: "int",
		go: "int",
		ruby: "Integer",
		typescript: "number",
		c: "int",
	},
	float: {
		python: "float",
		javascript: "number",
		java: "float",
		cpp: "float",
		csharp: "float",
		go: "float32",
		ruby: "Float",
		typescript: "number",
		c: "float",
	},
	double: {
		python: "float",
		javascript: "number",
		java: "double",
		cpp: "double",
		csharp: "double",
		go: "float64",
		ruby: "Float",
		typescript: "number",
		c: "double",
	},
	char: {
		python: "str",
		javascript: "string",
		java: "char",
		cpp: "char",
		csharp: "char",
		go: "rune",
		ruby: "String",
		typescript: "string",
		c: "char",
	},
	string: {
		python: "str",
		javascript: "string",
		java: "String",
		cpp: "string",
		csharp: "string",
		go: "string",
		ruby: "String",
		typescript: "string",
		c: "char*",
	},
	boolean: {
		python: "bool",
		javascript: "boolean",
		java: "boolean",
		cpp: "bool",
		csharp: "bool",
		go: "bool",
		ruby: "TrueClass | FalseClass",
		typescript: "boolean",
		c: "bool",
	},
	Array: {
		python: "List",
		javascript: "Array",
		java: "Array",
		cpp: "vector",
		csharp: "List",
		go: "[]",
		ruby: "Array",
		typescript: "Array",
		c: "Array",
	},
	List: {
		python: "List",
		javascript: "Array",
		java: "List",
		cpp: "vector",
		csharp: "List",
		go: "[]",
		ruby: "Array",
		typescript: "Array",
		c: "Array",
	},
	LinkedList: {
		python: "LinkedList",
		javascript: "LinkedList",
		java: "LinkedList",
		cpp: "LinkedList",
		csharp: "LinkedList",
		go: "LinkedList",
		ruby: "LinkedList",
		typescript: "LinkedList",
		c: "LinkedList",
	},
	Set: {
		python: "set",
		javascript: "Set",
		java: "Set",
		cpp: "set",
		csharp: "HashSet",
		go: "map[Type]struct{}",
		ruby: "Set",
		typescript: "Set",
		c: "Set",
	},
	Map: {
		python: "dict",
		javascript: "Map",
		java: "HashMap",
		cpp: "unordered_map",
		csharp: "Dictionary",
		go: "map",
		ruby: "Hash",
		typescript: "Map",
		c: "Map",
	},
	Queue: {
		python: "Queue",
		javascript: "Queue",
		java: "Queue",
		cpp: "queue",
		csharp: "Queue",
		go: "Queue",
		ruby: "Queue",
		typescript: "Queue",
		c: "Queue",
	},
	Stack: {
		python: "Stack",
		javascript: "Stack",
		java: "Stack",
		cpp: "stack",
		csharp: "Stack",
		go: "Stack",
		ruby: "Stack",
		typescript: "Stack",
		c: "Stack",
	},
	TreeNode: {
		python: "TreeNode",
		javascript: "TreeNode",
		java: "TreeNode",
		cpp: "TreeNode",
		csharp: "TreeNode",
		go: "TreeNode",
		ruby: "TreeNode",
		typescript: "TreeNode",
		c: "TreeNode",
	},
	GraphNode: {
		python: "GraphNode",
		javascript: "GraphNode",
		java: "GraphNode",
		cpp: "GraphNode",
		csharp: "GraphNode",
		go: "GraphNode",
		ruby: "GraphNode",
		typescript: "GraphNode",
		c: "GraphNode",
	},
};
